### ISSUE TITLE
Feature Request: allow page URL params to set defaults in form

### ISSUE THREAD

**Issue by jamestomasino** [morsecodemedia/utm-generator.morsecodemedia.com#1]
If a user goes to https://utm-generator.morsecodemedia.com/ and the URL includes UTM parameters, grab those and show them in the form on the page as the default values.

For instance: https://utm-generator.morsecodemedia.com/?utm_source=newsletter&utm_medium=email&utm_campaign=promo-2021

**Comment by morsecodemedia** [comment]
Great idea! 
I just pushed an update that has defaults on load (dfa773013386745c910bf14e66694bff2c5d3135)
I'll implement the feature request as you described, and fall back to the defaults if UTMs are not included.

**Comment by morsecodemedia** [comment]
@jamestomasino - Feature request has been implemented (0a1ffdcaf5a259b6c314547606570bfae4f94bf3) and pushed into production. Thank you for the suggestion.
