### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jamestomasino** [morsecodemedia/utm-generator.morsecodemedia.com#2]
Warn/inform users that UTM values are case-sensitive if they enter a mixed-case value. Perhaps a tool-tip or an info icon could display. When people are generating codes they often don't consider case sensitivity, so a warning and suggestion to lowercase would be benenficial.

**Comment by morsecodemedia** [comment]
Fantastic idea. In efforts to not be opinionated, I allow the validation to still pass on mixed-case values, but provides a warning, per your suggestion, that lets the user know that UTM values are case sensitive. (resolved in: 5bf31bb418abd75633735a282165df4a2c367203)
